### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by retokromer** [bertramlyons/vmanifest#3]
When I change an MD5 value in your test set, I got:

Comparing old md5s with new md5s...
/Users/test/Desktop/vmanifest: line 104: "22"-"22": syntax error: operand expected (error token is ""22"-"22"")

**Comment by bertramlyons** [comment]
Reto - thanks for the feedback. I tried to recreate and could not. Can you tell me which MD5 value you changed and how you changed it?

Thanks -- Bert

**Comment by retokromer** [comment]
Hi Bert, I cannot recreate the error neither. Therefore, I suppose, I did an error while trying. Sorry for the false alarm! Best regards, Reto
